
## Mesh generated by ConcentricCircleMeshGenerator and saved as "2DMonoblock.e"
[Mesh]
  [ccmg]
      type = ConcentricCircleMeshGenerator
      num_sectors = 36
      rings = '1 30 20 110'
      radii = '${radius_coolant} ${radius_CuCrZr} &{radius_Cu}'
      has_outer_square = on
      pitch = ${units 28 mm -> m}
      portion = left_half
      preserve_volumes = false
      smoothing_max_it = 3
  []
  [ssbsg1]
      type = SideSetsBetweenSubdomainsGenerator
      input = ccmg
      primary_block = '4'     # W
      paired_block = '3'      # Cu
      new_boundary = '4to3'
  []
  [ssbsg2]
      type = SideSetsBetweenSubdomainsGenerator
      input = ssbsg1
      primary_block = '3'     # Cu
      paired_block = '4'      # W
      new_boundary = '3to4'
  []
  [ssbsg3]
      type = SideSetsBetweenSubdomainsGenerator
      input = ssbsg2
      primary_block = '3'     # Cu
      paired_block = '2'      # CuCrZr
      new_boundary = '3to2'
  []
  [ssbsg4]
      type = SideSetsBetweenSubdomainsGenerator
      input = ssbsg3
      primary_block = '2'     # CuCrZr
      paired_block = '3'      # Cu
      new_boundary = '2to3'
  []
  [ssbsg5]
      type = SideSetsBetweenSubdomainsGenerator
      input = ssbsg4
      primary_block = '2'     # CuCrZr
      paired_block = '1'      # H2O
      new_boundary = '2to1'
  []
  [bdg]
      type = BlockDeletionGenerator
      input = ssbsg5
      block = '1'             # H2O
  []
[]
